server:
    port: 8081

spring:
    rabbitmq:
        host: ${RABBIT_HOST:rabbit_host}
        port: ${RABBIT_PORT:5672}
        username: ${RABBIT_USERNAME:lwejyugl}
        password: ${RABBIT_PASSWORD:password}
        virtual-host: ${RABBIT_VHOST:lwejyugl}
        queue:
            public:
            subscribe:
                socket_notify_friend_queue: "q_socket_notify_friend"
                socket_new_chat_message: "q_socket_new_chat_message"
                socket_update_chat_room: "q_socket_update_chat_room"
                socket_chat_room_member_ship: "q_socket_chat_room_member_ship"
                socket_chat_message_reaction: "q_socket_chat_message_reaction"
                socket_chat_message_recall: "q_socket_chat_message_recall"
